name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python 01_prod_regression_ci__tutorial.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          cml-send-comment report.md
          ls -l
          
      - name : staging1
       
        run: |
          git config --global user.name "rotheo"
          git config --global user.email "le_rotheo@hotmail.com"
          git  add  lm.dat metrics.txt report.md
          git commit -m "first commit"
          
           
          git push origin master
          
