name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python 01_prod_regression_ci__tutorial.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
      - name: execDocker
        run: |
          docker run --name theo_container -d server_app:latest
          docker cp lm.dat theo_container:
          docker exec -it theo_container /bin/sh
          
  
